INSERT INTO SAMPLE VALUES (1, NULL, NULL, NULL, FALSE, CURRENT_DATE, NULL, NULL);

INSERT INTO MASTER VALUES (1, 'コード１');
INSERT INTO MASTER VALUES (2, 'コード２');
INSERT INTO MASTER VALUES (3, 'コード３');
