CREATE TABLE SAMPLE (
  ID INT NOT NULL PRIMARY KEY,
  FIELD_TEXT VARCHAR(50),
  FIELD_TEXTAREA VARCHAR(300),
  FIELD_NUMBER INT,
  FIELD_DATE DATE,
  FIELD_SELECT INT,
  FIELD_RADIO INT,
  FIELD_SWITCH BOOLEAN
);

CREATE TABLE MASTER (
  CODE INT NOT NULL PRIMARY KEY,
  NAME VARCHAR(50)
);
