CREATE TABLE SAMPLE (
  ID INT NOT NULL PRIMARY KEY,
  TEXT VARCHAR(50),
  LONG_TEXT VARCHAR(300),
  NUMBER INT,
  BOOL BOOLEAN,
  DATE_VAL DATE
);

CREATE TABLE MASTER (
  CODE INT NOT NULL PRIMARY KEY,
  TEXT VARCHAR(50)
);
